name: Dockerfile Lint

on:
  push:
    branches:
      - '!main'
    paths:
      - 'Dockerfile*'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile*'

concurrency:
  group: dockerlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: lint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile
